// Party configuration
// Auto-generated by start.sh - DO NOT EDIT MANUALLY
// Last updated: 2025-11-04T16:53:39.000Z

export interface PartyInfo {
  displayName: string;
  partyId: string;
  role: string;
}

export const parties: Record<string, PartyInfo> = {
  alice: {
    displayName: 'Alice',
    partyId: 'party-04c2312f-76a7-4dfd-a670-429bbda19705::12208983065e6665749bb266298987aec45dfb948dfb392e2ed0b0295554119648d7',
    role: 'User'
  },
  bob: {
    displayName: 'Bob',
    partyId: 'party-3e0fdeb8-42f2-4370-9326-4d5cec9e11fd::12208983065e6665749bb266298987aec45dfb948dfb392e2ed0b0295554119648d7',
    role: 'User'
  },
  bank: {
    displayName: 'Bank',
    partyId: 'party-52177049-e339-4e75-bb8b-9a11f5c2abf6::12208983065e6665749bb266298987aec45dfb948dfb392e2ed0b0295554119648d7',
    role: 'Issuer'
  }
};

export const getAllParties = (): PartyInfo[] => {
  return Object.values(parties);
};

export const getPartyByName = (name: string): PartyInfo | undefined => {
  return parties[name.toLowerCase()];
};

export const getDisplayName = (partyId: string): string => {
  const party = Object.values(parties).find(p => p.partyId === partyId);
  return party?.displayName || partyId.split('::')[0] || partyId;
};
