// Party configuration
// Auto-generated by start.sh - DO NOT EDIT MANUALLY
// Last updated: 2025-11-10T16:38:10.000Z

export interface PartyInfo {
  displayName: string;
  partyId: string;
  role: string;
}

export const parties: Record<string, PartyInfo> = {
  alice: {
    displayName: 'Alice',
    partyId: 'party-9ef9fa0a-ef59-42e7-97ee-620b1256ba22::1220289114e84405bf946d2c14ddc90be0fa3021c11a88de275e6a3f4f73aaf4a93a',
    role: 'User'
  },
  bob: {
    displayName: 'Bob',
    partyId: 'party-921bce1a-055e-4c9b-8e39-56a758435ac5::1220289114e84405bf946d2c14ddc90be0fa3021c11a88de275e6a3f4f73aaf4a93a',
    role: 'User'
  },
  bank: {
    displayName: 'Bank',
    partyId: 'party-a6abfbdf-1c28-4a67-a47c-afc32a236ad4::1220289114e84405bf946d2c14ddc90be0fa3021c11a88de275e6a3f4f73aaf4a93a',
    role: 'Issuer'
  }
};

export const getAllParties = (): PartyInfo[] => {
  return Object.values(parties);
};

export const getPartyByName = (name: string): PartyInfo | undefined => {
  return parties[name.toLowerCase()];
};

export const getDisplayName = (partyId: string): string => {
  const party = Object.values(parties).find(p => p.partyId === partyId);
  return party?.displayName || partyId.split('::')[0] || partyId;
};
