// Party configuration
// Auto-generated by start.sh - DO NOT EDIT MANUALLY
// Last updated: 2025-10-31T20:03:47.000Z

export interface PartyInfo {
  displayName: string;
  partyId: string;
  role: string;
}

export const parties: Record<string, PartyInfo> = {
  alice: {
    displayName: 'Alice',
    partyId: 'party-46b7c660-12fb-4b63-a9ab-e0ea489986a3::1220f3ca8268fd0391371067c4f74e6e2b250c55455ea433948070534fc4bfe4e30e',
    role: 'User'
  },
  bob: {
    displayName: 'Bob',
    partyId: 'party-10bbf49f-d41b-48f8-8c36-443df0b67f62::1220f3ca8268fd0391371067c4f74e6e2b250c55455ea433948070534fc4bfe4e30e',
    role: 'User'
  },
  bank: {
    displayName: 'Bank',
    partyId: 'party-15b0d442-c159-4d08-954e-8c1d391c87a3::1220f3ca8268fd0391371067c4f74e6e2b250c55455ea433948070534fc4bfe4e30e',
    role: 'Issuer'
  }
};

export const getAllParties = (): PartyInfo[] => {
  return Object.values(parties);
};

export const getPartyByName = (name: string): PartyInfo | undefined => {
  return parties[name.toLowerCase()];
};

export const getDisplayName = (partyId: string): string => {
  const party = Object.values(parties).find(p => p.partyId === partyId);
  return party?.displayName || partyId.split('::')[0] || partyId;
};

