const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

console.log('Fetching party IDs from ledger...');

try {
  // Execute daml ledger list-parties command
  const output = execSync('daml ledger list-parties --host localhost --port 6865', {
    encoding: 'utf8',
    timeout: 10000
  });

  // Parse the output to extract party IDs
  const lines = output.split('\n');
  const parties = {};

  for (const line of lines) {
    // Look for lines containing party IDs
    // Format: "party-..." or lines with party names
    if (line.includes('party-')) {
      // Extract party ID (the full party-xxx::xxx string)
      const match = line.match(/(party-[a-f0-9-]+::[a-f0-9]+)/);
      if (match) {
        const partyId = match[1];
        
        // Try to identify which party this is based on the line content
        const lineLower = line.toLowerCase();
        if (lineLower.includes('alice')) {
          parties.alice = partyId;
        } else if (lineLower.includes('bob')) {
          parties.bob = partyId;
        } else if (lineLower.includes('bank')) {
          parties.bank = partyId;
        }
      }
    }
  }

  // Verify we found all parties
  if (!parties.alice || !parties.bob || !parties.bank) {
    console.error('Error: Could not find all party IDs');
    console.log('Found:', parties);
    process.exit(1);
  }

  console.log('Found party IDs:');
  console.log('  Alice:', parties.alice);
  console.log('  Bob:', parties.bob);
  console.log('  Bank:', parties.bank);

  // Create the updated parties.ts content
  const partiesContent = `// Party configuration
// Auto-generated by update-parties.js - DO NOT EDIT MANUALLY
// Last updated: ${new Date().toISOString()}

export interface PartyInfo {
    displayName: string;
    partyId: string;
    role: string;
  }
  
  export const parties: Record<string, PartyInfo> = {
    alice: {
      displayName: 'Alice',
      partyId: '${parties.alice}',
      role: 'User'
    },
    bob: {
      displayName: 'Bob',
      partyId: '${parties.bob}',
      role: 'User'
    },
    bank: {
      displayName: 'Bank',
      partyId: '${parties.bank}',
      role: 'Issuer'
    }
  };
  
  // Helper function to get party by display name
  export const getPartyByName = (name: string): PartyInfo | undefined => {
    const key = name.toLowerCase();
    return parties[key];
  };
  
  // Helper function to get display name from party ID
  export const getDisplayName = (partyId: string): string => {
    const party = Object.values(parties).find(p => p.partyId === partyId);
    
    return party?.displayName || partyId.split('::')[0];
  };
  
  // Get all parties as an array
  export const getAllParties = (): PartyInfo[] => {
    return Object.values(parties);
  };`;

  // Write to parties.ts
  const partiesPath = path.join(__dirname, 'ui', 'src', 'config', 'parties.ts');
  fs.writeFileSync(partiesPath, partiesContent, 'utf8');

  console.log('✓ Successfully updated ui/src/config/parties.ts');
  process.exit(0);

} catch (error) {
  console.error('Error fetching or updating party IDs:', error.message);
  process.exit(1);
}